# Site Configuration

# Theme
theme: jekyll-theme-chirpy

# Language and timezone
lang: en
timezone: Europe/London

# Site Metadata for SEO and Feeds
title: Teddy McDermott
tagline: "London-based Physics Graduate from UCL, pursuing a career in Software development & IT."
description: >-
  Personal blog and portfolio of Teddy McDermott — UCL Physics graduate, exploring software engineering, computing, and technology.

# Your site URL (e.g., GitHub Pages repo URL)
url: "https://wayworm.github.io" # Replace with your actual deployment URL

# Social Media & Author Info
github:
  username: wayworm

social:
  name: Teddy McDermott
  email: teddyraymcdermott@gmail.com
  links:
    - https://github.com/wayworm
    - mailto:teddyraymcdermott@gmail.com
    - https://www.linkedin.com/in/teddy-mcdermott-5756bb257/

# Webmaster Tools (SEO Verification)
webmaster_verifications:
  google:
  bing:
  yandex:
  facebook:

# Analytics (Optional — Enable one if desired)
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views
pageviews:
  provider:

# Theme mode (dark, light, or leave empty for system default)
theme_mode:

# Avatar image (sidebar)
avatar: "/images/me.jpg"

# Social preview image (for link sharing)
social_preview_image:

# Table of Contents (TOC)
toc: true

# Comments (choose one and configure)
comments:
  provider: # disqus | utterances | giscus
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Self-hosted assets
assets:
  self_host:
    enabled:
    env:

# PWA (Progressive Web App) settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"

# Pagination
paginate: 10

# Base URL (usually empty for GitHub Pages)
baseurl: ""

# Markdown and Syntax Highlighting
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections (used for tabs and pages)
collections:
  tabs:
    output: true
    sort_by: order

# Default configurations
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Sass and HTML Compression
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Files and folders to exclude from the build
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# Jekyll Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
